# Generated by Django 5.2 on 2025-05-01 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyForRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_type', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('area', models.FloatField()),
                ('beds', models.IntegerField()),
                ('bathrooms', models.FloatField()),
                ('balconies', models.IntegerField()),
                ('furnishing', models.CharField(max_length=50)),
                ('area_rate', models.FloatField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('rent', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyForSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_type', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('area', models.FloatField()),
                ('beds', models.IntegerField()),
                ('bathrooms', models.FloatField()),
                ('balconies', models.IntegerField()),
                ('furnishing', models.CharField(max_length=50)),
                ('area_rate', models.FloatField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('sale_price', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
