# Generated by Django 5.2 on 2025-05-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyforrent',
            old_name='images',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='propertyforsale',
            old_name='images',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='propertyforrent',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='propertyforrent',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='propertyforrent',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='propertyforrent',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='propertyforsale',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='propertyforsale',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='propertyforsale',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='propertyforsale',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
    ]
