# Generated by Django 5.2 on 2025-05-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_rename_images_propertyforrent_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyforsale',
            name='total_units',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='propertyforsale',
            name='units_sold',
            field=models.IntegerField(default=0),
        ),
    ]
